name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'stable'
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run Flutter Test
      run: flutter test
