name: Flutter Test CI

on:
  push:
    branches:
      - main
    paths:
    - '**.dart'
  pull_request:
    branches:
      - main
    paths:
    - '**.dart'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'  # You can specify a version if needed
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run Flutter Test
      run: flutter test
